# Generated by Django 5.2.8 on 2025-11-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('product_details', models.TextField(blank=True, null=True)),
                ('minable_coins', models.CharField(help_text='Comma-separated list, e.g. BTC, BCH, BSV', max_length=255)),
                ('hashrate', models.CharField(max_length=100)),
                ('power', models.CharField(max_length=100)),
                ('algorithm', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
