# Generated by Django 5.2.8 on 2025-11-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hosting_fee_per_kw',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee per kilowatt for hosting', max_digits=10, null=True),
        ),
    ]
