# Generated by Django 5.2.8 on 2025-11-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_product_hosting_fee_per_kw'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hosting_fee_per_kw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_hashrate', models.CharField(blank=True, max_length=100, null=True)),
                ('total_power', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bundle_offers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(to='AdminApp.product')),
            ],
        ),
    ]
