# Generated by Django 5.2.8 on 2025-12-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_details',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('air', 'Air Cooled'), ('immersion', 'Immersion'), ('hydro', 'Hydro'), ('home', 'Home Miner')], default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Required only if delivery type is Future', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_type',
            field=models.CharField(choices=[('spot', 'Spot'), ('future', 'Future')], default='spot', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='efficiency',
            field=models.CharField(blank=True, help_text='Example: 29.5 J/TH', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Is the product currently available?'),
        ),
        migrations.AddField(
            model_name='product',
            name='noise',
            field=models.CharField(blank=True, help_text='Example: 75 dB', max_length=50, null=True),
        ),
    ]
