# Generated by Django 5.2.8 on 2025-12-24 08:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_remove_product_product_details_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundleoffer',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
