# Generated by Django 5.2.8 on 2025-12-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_alter_bundleoffer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundleoffer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bundle_offers/'),
        ),
    ]
