# Generated by Django 5.2.8 on 2025-12-24 12:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_alter_bundleoffer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundleoffer',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
