# Generated by Django 5.2.8 on 2025-12-25 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_alter_bundleoffer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundleoffer',
            name='products',
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='AdminApp.bundleoffer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.product')),
            ],
            options={
                'unique_together': {('bundle', 'product')},
            },
        ),
    ]
