# Generated by Django 5.2.8 on 2025-12-25 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_remove_bundleoffer_products_bundleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundleitem',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='AdminApp.bundleoffer'),
        ),
    ]
