# Generated by Django 5.2.8 on 2026-01-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0011_blog_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='USD', help_text='Example: USD, INR, EUR', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage (0–100)'),
        ),
        migrations.AddField(
            model_name='product',
            name='network_interface',
            field=models.CharField(blank=True, help_text='Example: Ethernet', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='operating_temperature',
            field=models.CharField(blank=True, help_text='Example: 0°C ,40°C', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='plug_socket_type',
            field=models.CharField(blank=True, help_text='Example: US / EU / UK', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='power_cord_information',
            field=models.CharField(blank=True, help_text='Example: Included / Not Included', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='voltage',
            field=models.CharField(blank=True, help_text='Example: 200-240V', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, help_text='Example: 6 Months, 1 Year', max_length=100, null=True),
        ),
    ]
