# Generated by Django 5.2.8 on 2025-11-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_alter_cartitem_unique_together_cartitem_bundle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_address',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
