# Generated by Django 5.2.8 on 2025-12-10 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_order_delivery_address_user_shipping_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('items', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING_CONTACT', 'Pending Contact'), ('CONTACTED', 'Contacted'), ('CANCELLED', 'Cancelled')], default='PENDING_CONTACT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosting_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
