# Generated by Django 5.2.8 on 2025-12-15 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_hostingrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostingrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='hostingrequest',
            name='hosting_location',
            field=models.CharField(choices=[('US', 'United States'), ('ET', 'Ethiopia'), ('UAE', 'UAE')], default='US', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostingrequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostingrequest',
            name='setup_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hostingrequest',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostingrequest',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='hostingrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
