# Generated by Django 5.2.8 on 2025-12-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingrequest',
            name='monitoring_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostingrequest',
            name='monitoring_type',
            field=models.CharField(blank=True, choices=[('internal', 'Cryptonite Platform'), ('external', 'Third Party Platform')], max_length=20, null=True),
        ),
    ]
